import { CalendarEvent } from '../types';

export function createGoogleCalendarUrl(event: CalendarEvent): string {
  const title = encodeURIComponent(event.title);
  const details = encodeURIComponent(
    `${event.description}\n\nGenerated by Audio & Video Intelligence Engine`
  );
  const location = encodeURIComponent(event.location || 'Remote / Online');

  let startDate: Date;
  try {
    startDate = new Date(event.approximateDateTime);
    if (isNaN(startDate.getTime())) {
      startDate = new Date(Date.now() + 86400000 * 2); // default 2 days ahead
    }
  } catch {
    startDate = new Date(Date.now() + 86400000 * 2);
  }

  const durationMs = (event.durationMinutes || 60) * 60 * 1000;
  const endDate = new Date(startDate.getTime() + durationMs);

  const formatGCalDate = (d: Date) => {
    return d.toISOString().replace(/-|:|\.\d\d\d/g, '');
  };

  const dates = `${formatGCalDate(startDate)}/${formatGCalDate(endDate)}`;

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&location=${location}&dates=${dates}`;
}

export function downloadIcsFile(event: CalendarEvent): void {
  let startDate: Date;
  try {
    startDate = new Date(event.approximateDateTime);
    if (isNaN(startDate.getTime())) {
      startDate = new Date(Date.now() + 86400000 * 2);
    }
  } catch {
    startDate = new Date(Date.now() + 86400000 * 2);
  }

  const durationMs = (event.durationMinutes || 60) * 60 * 1000;
  const endDate = new Date(startDate.getTime() + durationMs);

  const formatIcsDate = (d: Date) => {
    return d.toISOString().replace(/-|:|\.\d\d\d/g, '');
  };

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//AI Studio//Audio Video Intelligence Engine//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `UID:${event.id || 'evt'}-${Date.now()}@aistudio.build`,
    `DTSTAMP:${formatIcsDate(new Date())}`,
    `DTSTART:${formatIcsDate(startDate)}`,
    `DTEND:${formatIcsDate(endDate)}`,
    `SUMMARY:${event.title.replace(/\n/g, ' ')}`,
    `DESCRIPTION:${event.description.replace(/\n/g, '\\n')}`,
    `LOCATION:${(event.location || 'Remote').replace(/\n/g, ' ')}`,
    'STATUS:CONFIRMED',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${event.title.replace(/[^a-zA-Z0-9_-]/g, '_')}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadAllIcsFiles(events: CalendarEvent[]): void {
  if (!events || events.length === 0) return;

  const now = new Date();
  const formatIcsDate = (d: Date) => d.toISOString().replace(/-|:|\.\d\d\d/g, '');

  const vEvents = events.map((event, idx) => {
    let startDate: Date;
    try {
      startDate = new Date(event.approximateDateTime);
      if (isNaN(startDate.getTime())) {
        startDate = new Date(Date.now() + 86400000 * (idx + 1));
      }
    } catch {
      startDate = new Date(Date.now() + 86400000 * (idx + 1));
    }
    const durationMs = (event.durationMinutes || 60) * 60 * 1000;
    const endDate = new Date(startDate.getTime() + durationMs);

    return [
      'BEGIN:VEVENT',
      `UID:${event.id || 'evt'}-${idx}-${Date.now()}@aistudio.build`,
      `DTSTAMP:${formatIcsDate(now)}`,
      `DTSTART:${formatIcsDate(startDate)}`,
      `DTEND:${formatIcsDate(endDate)}`,
      `SUMMARY:${event.title.replace(/\n/g, ' ')}`,
      `DESCRIPTION:${event.description.replace(/\n/g, '\\n')}`,
      `LOCATION:${(event.location || 'Remote').replace(/\n/g, ' ')}`,
      'STATUS:CONFIRMED',
      'END:VEVENT',
    ].join('\r\n');
  });

  const icsFull = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//AI Studio//Audio Video Intelligence Engine//EN',
    'CALSCALE:GREGORIAN',
    ...vEvents,
    'END:VCALENDAR',
  ].join('\r\n');

  const blob = new Blob([icsFull], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `session_calendar_schedule.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
